export const themes = [
  {
    id: "notion",
    name: "Notion",
    swatch: ["#3b372e", "#c0762a", "#e8e4da"],
    light: {
      background: "#f7f5ef",
      foreground: "#2d2a24",
      card: "#ffffff",
      "card-foreground": "#2d2a24",
      primary: "#c0762a",
      "primary-foreground": "#ffffff",
      secondary: "#ece9df",
      "secondary-foreground": "#2d2a24",
      muted: "#ece9df",
      "muted-foreground": "#6b6560",
      accent: "#ece9df",
      "accent-foreground": "#2d2a24",
      destructive: "#c0533f",
      "destructive-foreground": "#ffffff",
      border: "rgba(45, 42, 36, 0.14)",
      input: "rgba(45, 42, 36, 0.14)",
      ring: "rgba(192, 118, 42, 0.4)",
    },
    dark: {
      background: "#3b372e",
      foreground: "#e8e4da",
      card: "#413d34",
      "card-foreground": "#e8e4da",
      primary: "#e8e4da",
      "primary-foreground": "#2d2a24",
      secondary: "#444037",
      "secondary-foreground": "#e8e4da",
      muted: "#413d34",
      "muted-foreground": "rgba(232, 228, 218, 0.55)",
      accent: "#444037",
      "accent-foreground": "#e8e4da",
      destructive: "#d66a5a",
      "destructive-foreground": "#ffffff",
      border: "rgba(232, 228, 218, 0.14)",
      input: "rgba(232, 228, 218, 0.14)",
      ring: "rgba(232, 228, 218, 0.4)",
    },
  },
  {
    id: "github",
    name: "GitHub",
    swatch: ["#0d1117", "#3fb950", "#c9d1d9"],
    light: {
      background: "#ffffff",
      foreground: "#24292f",
      card: "#ffffff",
      "card-foreground": "#24292f",
      primary: "#1a7f37",
      "primary-foreground": "#ffffff",
      secondary: "#f6f8fa",
      "secondary-foreground": "#24292f",
      muted: "#f6f8fa",
      "muted-foreground": "#57606a",
      accent: "#f6f8fa",
      "accent-foreground": "#1a7f37",
      destructive: "#cf222e",
      "destructive-foreground": "#ffffff",
      border: "#d0d7de",
      input: "#d0d7de",
      ring: "#1a7f37",
    },
    dark: {
      background: "#0d1117",
      foreground: "#c9d1d9",
      card: "#161b22",
      "card-foreground": "#c9d1d9",
      primary: "#3fb950",
      "primary-foreground": "#0d1117",
      secondary: "#161b22",
      "secondary-foreground": "#c9d1d9",
      muted: "#161b22",
      "muted-foreground": "#8b949e",
      accent: "#1f2937",
      "accent-foreground": "#3fb950",
      destructive: "#f85149",
      "destructive-foreground": "#ffffff",
      border: "#30363d",
      input: "#30363d",
      ring: "#3fb950",
    },
  },
  {
    id: "supabase",
    name: "Supabase",
    swatch: ["#1c1c1c", "#3ecf8e", "#e8e8e8"],
    light: {
      background: "#ffffff",
      foreground: "#1c1c1c",
      card: "#ffffff",
      "card-foreground": "#1c1c1c",
      primary: "#3ecf8e",
      "primary-foreground": "#1c1c1c",
      secondary: "#f0fdf4",
      "secondary-foreground": "#1c1c1c",
      muted: "#f0fdf4",
      "muted-foreground": "#6b7280",
      accent: "#dcfce7",
      "accent-foreground": "#166534",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#e5e7eb",
      input: "#e5e7eb",
      ring: "#3ecf8e",
    },
    dark: {
      background: "#1c1c1c",
      foreground: "#e8e8e8",
      card: "#262626",
      "card-foreground": "#e8e8e8",
      primary: "#3ecf8e",
      "primary-foreground": "#1c1c1c",
      secondary: "#262626",
      "secondary-foreground": "#e8e8e8",
      muted: "#262626",
      "muted-foreground": "#9ca3af",
      accent: "#064e3b",
      "accent-foreground": "#3ecf8e",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#333333",
      input: "#333333",
      ring: "#3ecf8e",
    },
  },
  {
    id: "vercel",
    name: "Vercel",
    swatch: ["#000000", "#f5a623", "#ededed"],
    light: {
      background: "#ffffff",
      foreground: "#171717",
      card: "#ffffff",
      "card-foreground": "#171717",
      primary: "#f5a623",
      "primary-foreground": "#ffffff",
      secondary: "#f5f5f5",
      "secondary-foreground": "#171717",
      muted: "#f5f5f5",
      "muted-foreground": "#666666",
      accent: "#f5f5f5",
      "accent-foreground": "#f5a623",
      destructive: "#ee0000",
      "destructive-foreground": "#ffffff",
      border: "#eaeaea",
      input: "#eaeaea",
      ring: "#f5a623",
    },
    dark: {
      background: "#000000",
      foreground: "#ededed",
      card: "#111111",
      "card-foreground": "#ededed",
      primary: "#f5a623",
      "primary-foreground": "#000000",
      secondary: "#111111",
      "secondary-foreground": "#ededed",
      muted: "#111111",
      "muted-foreground": "#666666",
      accent: "#1a1a1a",
      "accent-foreground": "#f5a623",
      destructive: "#ee0000",
      "destructive-foreground": "#ffffff",
      border: "#333333",
      input: "#333333",
      ring: "#f5a623",
    },
  },
  {
    id: "tailwind",
    name: "Tailwind",
    swatch: ["#0f172a", "#f59e0b", "#f8fafc"],
    light: {
      background: "#ffffff",
      foreground: "#0f172a",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      primary: "#d97706",
      "primary-foreground": "#ffffff",
      secondary: "#f1f5f9",
      "secondary-foreground": "#0f172a",
      muted: "#f1f5f9",
      "muted-foreground": "#64748b",
      accent: "#f1f5f9",
      "accent-foreground": "#d97706",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#d97706",
    },
    dark: {
      background: "#0f172a",
      foreground: "#f8fafc",
      card: "#1e293b",
      "card-foreground": "#f8fafc",
      primary: "#fbbf24",
      "primary-foreground": "#0f172a",
      secondary: "#1e293b",
      "secondary-foreground": "#f8fafc",
      muted: "#1e293b",
      "muted-foreground": "#94a3b8",
      accent: "#1e3a5f",
      "accent-foreground": "#fbbf24",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#334155",
      input: "#334155",
      ring: "#fbbf24",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    swatch: ["#0a0e1a", "#a78bfa", "#e0e7ff"],
    light: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      primary: "#7c3aed",
      "primary-foreground": "#ffffff",
      secondary: "#eef2ff",
      "secondary-foreground": "#312e81",
      muted: "#eef2ff",
      "muted-foreground": "#6366f1",
      accent: "#e0e7ff",
      "accent-foreground": "#312e81",
      destructive: "#ef4444",
      "destructive-foreground": "#ffffff",
      border: "#c7d2fe",
      input: "#c7d2fe",
      ring: "#7c3aed",
    },
    dark: {
      background: "#0a0e1a",
      foreground: "#e0e7ff",
      card: "#111827",
      "card-foreground": "#e0e7ff",
      primary: "#a78bfa",
      "primary-foreground": "#0a0e1a",
      secondary: "#1e1b4b",
      "secondary-foreground": "#c7d2fe",
      muted: "#1e1b4b",
      "muted-foreground": "#a5b4fc",
      accent: "#312e81",
      "accent-foreground": "#a5b4fc",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#1e1b4b",
      input: "#1e1b4b",
      ring: "#a78bfa",
    },
  },
  {
    id: "forest",
    name: "Forest",
    swatch: ["#1a2e1a", "#22c55e", "#dcfce7"],
    light: {
      background: "#f0fdf4",
      foreground: "#14532d",
      card: "#ffffff",
      "card-foreground": "#14532d",
      primary: "#16a34a",
      "primary-foreground": "#ffffff",
      secondary: "#dcfce7",
      "secondary-foreground": "#14532d",
      muted: "#dcfce7",
      "muted-foreground": "#15803d",
      accent: "#bbf7d0",
      "accent-foreground": "#14532d",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#bbf7d0",
      input: "#bbf7d0",
      ring: "#16a34a",
    },
    dark: {
      background: "#1a2e1a",
      foreground: "#dcfce7",
      card: "#1e3a1e",
      "card-foreground": "#dcfce7",
      primary: "#4ade80",
      "primary-foreground": "#1a2e1a",
      secondary: "#1e3a1e",
      "secondary-foreground": "#dcfce7",
      muted: "#1e3a1e",
      "muted-foreground": "#86efac",
      accent: "#166534",
      "accent-foreground": "#86efac",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#166534",
      input: "#166534",
      ring: "#4ade80",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    swatch: ["#1c1017", "#f97316", "#ffedd5"],
    light: {
      background: "#fffbeb",
      foreground: "#431407",
      card: "#ffffff",
      "card-foreground": "#431407",
      primary: "#ea580c",
      "primary-foreground": "#ffffff",
      secondary: "#ffedd5",
      "secondary-foreground": "#431407",
      muted: "#ffedd5",
      "muted-foreground": "#c2410c",
      accent: "#fed7aa",
      "accent-foreground": "#431407",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#fed7aa",
      input: "#fed7aa",
      ring: "#ea580c",
    },
    dark: {
      background: "#1c1017",
      foreground: "#ffedd5",
      card: "#271520",
      "card-foreground": "#ffedd5",
      primary: "#fb923c",
      "primary-foreground": "#1c1017",
      secondary: "#271520",
      "secondary-foreground": "#ffedd5",
      muted: "#271520",
      "muted-foreground": "#fdba74",
      accent: "#7c2d12",
      "accent-foreground": "#fdba74",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#7c2d12",
      input: "#7c2d12",
      ring: "#fb923c",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    swatch: ["#0a1628", "#06b6d4", "#cffafe"],
    light: {
      background: "#f0fdfa",
      foreground: "#134e4a",
      card: "#ffffff",
      "card-foreground": "#134e4a",
      primary: "#0891b2",
      "primary-foreground": "#ffffff",
      secondary: "#ccfbf1",
      "secondary-foreground": "#134e4a",
      muted: "#ccfbf1",
      "muted-foreground": "#0d9488",
      accent: "#99f6e4",
      "accent-foreground": "#134e4a",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#99f6e4",
      input: "#99f6e4",
      ring: "#0891b2",
    },
    dark: {
      background: "#0a1628",
      foreground: "#cffafe",
      card: "#0f2035",
      "card-foreground": "#cffafe",
      primary: "#22d3ee",
      "primary-foreground": "#0a1628",
      secondary: "#0f2035",
      "secondary-foreground": "#cffafe",
      muted: "#0f2035",
      "muted-foreground": "#67e8f9",
      accent: "#155e75",
      "accent-foreground": "#67e8f9",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#155e75",
      input: "#155e75",
      ring: "#22d3ee",
    },
  },
  {
    id: "rose",
    name: "Rose",
    swatch: ["#1c1019", "#f43f5e", "#ffe4e6"],
    light: {
      background: "#fff1f2",
      foreground: "#4c0519",
      card: "#ffffff",
      "card-foreground": "#4c0519",
      primary: "#e11d48",
      "primary-foreground": "#ffffff",
      secondary: "#ffe4e6",
      "secondary-foreground": "#4c0519",
      muted: "#ffe4e6",
      "muted-foreground": "#be123c",
      accent: "#fecdd3",
      "accent-foreground": "#4c0519",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#fecdd3",
      input: "#fecdd3",
      ring: "#e11d48",
    },
    dark: {
      background: "#1c1019",
      foreground: "#ffe4e6",
      card: "#2a1520",
      "card-foreground": "#ffe4e6",
      primary: "#fb7185",
      "primary-foreground": "#1c1019",
      secondary: "#2a1520",
      "secondary-foreground": "#ffe4e6",
      muted: "#2a1520",
      "muted-foreground": "#fda4af",
      accent: "#881337",
      "accent-foreground": "#fda4af",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#881337",
      input: "#881337",
      ring: "#fb7185",
    },
  },
  {
    id: "slate",
    name: "Slate",
    swatch: ["#0f172a", "#e2e8f0", "#1e293b"],
    light: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      primary: "#475569",
      "primary-foreground": "#ffffff",
      secondary: "#e2e8f0",
      "secondary-foreground": "#0f172a",
      muted: "#e2e8f0",
      "muted-foreground": "#64748b",
      accent: "#e2e8f0",
      "accent-foreground": "#475569",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#cbd5e1",
      input: "#cbd5e1",
      ring: "#475569",
    },
    dark: {
      background: "#0f172a",
      foreground: "#e2e8f0",
      card: "#1e293b",
      "card-foreground": "#e2e8f0",
      primary: "#94a3b8",
      "primary-foreground": "#0f172a",
      secondary: "#1e293b",
      "secondary-foreground": "#e2e8f0",
      muted: "#1e293b",
      "muted-foreground": "#94a3b8",
      accent: "#334155",
      "accent-foreground": "#94a3b8",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#334155",
      input: "#334155",
      ring: "#94a3b8",
    },
  },
  {
    id: "amber",
    name: "Amber",
    swatch: ["#1c1408", "#f59e0b", "#fef3c7"],
    light: {
      background: "#fffbeb",
      foreground: "#451a03",
      card: "#ffffff",
      "card-foreground": "#451a03",
      primary: "#d97706",
      "primary-foreground": "#ffffff",
      secondary: "#fef3c7",
      "secondary-foreground": "#451a03",
      muted: "#fef3c7",
      "muted-foreground": "#b45309",
      accent: "#fde68a",
      "accent-foreground": "#451a03",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#fde68a",
      input: "#fde68a",
      ring: "#d97706",
    },
    dark: {
      background: "#1c1408",
      foreground: "#fef3c7",
      card: "#2a1f0e",
      "card-foreground": "#fef3c7",
      primary: "#fbbf24",
      "primary-foreground": "#1c1408",
      secondary: "#2a1f0e",
      "secondary-foreground": "#fef3c7",
      muted: "#2a1f0e",
      "muted-foreground": "#fcd34d",
      accent: "#92400e",
      "accent-foreground": "#fcd34d",
      destructive: "#f87171",
      "destructive-foreground": "#ffffff",
      border: "#92400e",
      input: "#92400e",
      ring: "#fbbf24",
    },
  },
]

export function getThemeById(id) {
  return themes.find((t) => t.id === id) || themes[0]
}
