export const themes = [
  {
    id: "notion",
    name: "Notion",
    swatch: ["#3b372e", "#c0762a", "#e8e4da"],
    styles: {
      light: {
        background: "#f7f5ef",
        foreground: "#2d2a24",
        card: "#ffffff",
        "card-foreground": "#2d2a24",
        popover: "#ffffff",
        "popover-foreground": "#2d2a24",
        primary: "#c0762a",
        "primary-foreground": "#ffffff",
        secondary: "#ece9df",
        "secondary-foreground": "#2d2a24",
        muted: "#ece9df",
        "muted-foreground": "#6b6560",
        accent: "#ece9df",
        "accent-foreground": "#2d2a24",
        destructive: "#c0533f",
        "destructive-foreground": "#ffffff",
        border: "rgba(45, 42, 36, 0.14)",
        input: "rgba(45, 42, 36, 0.14)",
        ring: "rgba(192, 118, 42, 0.4)",
        "chart-1": "#c0762a",
        "chart-2": "#d4943f",
        "chart-3": "#e8b060",
        "chart-4": "#f0c880",
        "chart-5": "#f8dfa0",
        sidebar: "#f0ede5",
        "sidebar-foreground": "#2d2a24",
        "sidebar-primary": "#c0762a",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#ece9df",
        "sidebar-accent-foreground": "#2d2a24",
        "sidebar-border": "rgba(45, 42, 36, 0.14)",
        "sidebar-ring": "rgba(192, 118, 42, 0.4)",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#3b372e",
        foreground: "#e8e4da",
        card: "#413d34",
        "card-foreground": "#e8e4da",
        popover: "#413d34",
        "popover-foreground": "#e8e4da",
        primary: "#e8e4da",
        "primary-foreground": "#2d2a24",
        secondary: "#444037",
        "secondary-foreground": "#e8e4da",
        muted: "#413d34",
        "muted-foreground": "rgba(232, 228, 218, 0.55)",
        accent: "#444037",
        "accent-foreground": "#e8e4da",
        destructive: "#d66a5a",
        "destructive-foreground": "#ffffff",
        border: "rgba(232, 228, 218, 0.14)",
        input: "rgba(232, 228, 218, 0.14)",
        ring: "rgba(232, 228, 218, 0.4)",
        "chart-1": "#e8e4da",
        "chart-2": "#d4cfc5",
        "chart-3": "#c0bab0",
        "chart-4": "#aca69c",
        "chart-5": "#98928a",
        sidebar: "#353128",
        "sidebar-foreground": "#e8e4da",
        "sidebar-primary": "#e8e4da",
        "sidebar-primary-foreground": "#2d2a24",
        "sidebar-accent": "#444037",
        "sidebar-accent-foreground": "#e8e4da",
        "sidebar-border": "rgba(232, 228, 218, 0.14)",
        "sidebar-ring": "rgba(232, 228, 218, 0.4)",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "github",
    name: "GitHub",
    swatch: ["#0d1117", "#3fb950", "#c9d1d9"],
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#24292f",
        card: "#ffffff",
        "card-foreground": "#24292f",
        popover: "#ffffff",
        "popover-foreground": "#24292f",
        primary: "#1a7f37",
        "primary-foreground": "#ffffff",
        secondary: "#f6f8fa",
        "secondary-foreground": "#24292f",
        muted: "#f6f8fa",
        "muted-foreground": "#57606a",
        accent: "#f6f8fa",
        "accent-foreground": "#1a7f37",
        destructive: "#cf222e",
        "destructive-foreground": "#ffffff",
        border: "#d0d7de",
        input: "#d0d7de",
        ring: "#1a7f37",
        "chart-1": "#1a7f37",
        "chart-2": "#2da44e",
        "chart-3": "#3fb950",
        "chart-4": "#56d364",
        "chart-5": "#7ee787",
        sidebar: "#f6f8fa",
        "sidebar-foreground": "#24292f",
        "sidebar-primary": "#1a7f37",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f6f8fa",
        "sidebar-accent-foreground": "#1a7f37",
        "sidebar-border": "#d0d7de",
        "sidebar-ring": "#1a7f37",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0d1117",
        foreground: "#c9d1d9",
        card: "#161b22",
        "card-foreground": "#c9d1d9",
        popover: "#161b22",
        "popover-foreground": "#c9d1d9",
        primary: "#3fb950",
        "primary-foreground": "#0d1117",
        secondary: "#161b22",
        "secondary-foreground": "#c9d1d9",
        muted: "#161b22",
        "muted-foreground": "#8b949e",
        accent: "#1f2937",
        "accent-foreground": "#3fb950",
        destructive: "#f85149",
        "destructive-foreground": "#ffffff",
        border: "#30363d",
        input: "#30363d",
        ring: "#3fb950",
        "chart-1": "#3fb950",
        "chart-2": "#56d364",
        "chart-3": "#7ee787",
        "chart-4": "#aff5b4",
        "chart-5": "#d2facc",
        sidebar: "#0d1117",
        "sidebar-foreground": "#c9d1d9",
        "sidebar-primary": "#3fb950",
        "sidebar-primary-foreground": "#0d1117",
        "sidebar-accent": "#1f2937",
        "sidebar-accent-foreground": "#3fb950",
        "sidebar-border": "#30363d",
        "sidebar-ring": "#3fb950",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "supabase",
    name: "Supabase",
    swatch: ["#1c1c1c", "#3ecf8e", "#e8e8e8"],
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#1c1c1c",
        card: "#ffffff",
        "card-foreground": "#1c1c1c",
        popover: "#ffffff",
        "popover-foreground": "#1c1c1c",
        primary: "#3ecf8e",
        "primary-foreground": "#1c1c1c",
        secondary: "#f0fdf4",
        "secondary-foreground": "#1c1c1c",
        muted: "#f0fdf4",
        "muted-foreground": "#6b7280",
        accent: "#dcfce7",
        "accent-foreground": "#166534",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#e5e7eb",
        input: "#e5e7eb",
        ring: "#3ecf8e",
        "chart-1": "#3ecf8e",
        "chart-2": "#2dd4bf",
        "chart-3": "#14b8a6",
        "chart-4": "#0d9488",
        "chart-5": "#0f766e",
        sidebar: "#f9fafb",
        "sidebar-foreground": "#1c1c1c",
        "sidebar-primary": "#3ecf8e",
        "sidebar-primary-foreground": "#1c1c1c",
        "sidebar-accent": "#dcfce7",
        "sidebar-accent-foreground": "#166534",
        "sidebar-border": "#e5e7eb",
        "sidebar-ring": "#3ecf8e",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1c1c1c",
        foreground: "#e8e8e8",
        card: "#262626",
        "card-foreground": "#e8e8e8",
        popover: "#262626",
        "popover-foreground": "#e8e8e8",
        primary: "#3ecf8e",
        "primary-foreground": "#1c1c1c",
        secondary: "#262626",
        "secondary-foreground": "#e8e8e8",
        muted: "#262626",
        "muted-foreground": "#9ca3af",
        accent: "#064e3b",
        "accent-foreground": "#3ecf8e",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#333333",
        input: "#333333",
        ring: "#3ecf8e",
        "chart-1": "#3ecf8e",
        "chart-2": "#6ee7b7",
        "chart-3": "#a7f3d0",
        "chart-4": "#d1fae5",
        "chart-5": "#ecfdf5",
        sidebar: "#1c1c1c",
        "sidebar-foreground": "#e8e8e8",
        "sidebar-primary": "#3ecf8e",
        "sidebar-primary-foreground": "#1c1c1c",
        "sidebar-accent": "#064e3b",
        "sidebar-accent-foreground": "#3ecf8e",
        "sidebar-border": "#333333",
        "sidebar-ring": "#3ecf8e",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "vercel",
    name: "Vercel",
    swatch: ["#000000", "#f5a623", "#ededed"],
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#171717",
        card: "#ffffff",
        "card-foreground": "#171717",
        popover: "#ffffff",
        "popover-foreground": "#171717",
        primary: "#f5a623",
        "primary-foreground": "#ffffff",
        secondary: "#f5f5f5",
        "secondary-foreground": "#171717",
        muted: "#f5f5f5",
        "muted-foreground": "#666666",
        accent: "#f5f5f5",
        "accent-foreground": "#f5a623",
        destructive: "#ee0000",
        "destructive-foreground": "#ffffff",
        border: "#eaeaea",
        input: "#eaeaea",
        ring: "#f5a623",
        "chart-1": "#f5a623",
        "chart-2": "#e09800",
        "chart-3": "#cc8a00",
        "chart-4": "#b87c00",
        "chart-5": "#a36e00",
        sidebar: "#fafafa",
        "sidebar-foreground": "#171717",
        "sidebar-primary": "#f5a623",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f5f5f5",
        "sidebar-accent-foreground": "#f5a623",
        "sidebar-border": "#eaeaea",
        "sidebar-ring": "#f5a623",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#000000",
        foreground: "#ededed",
        card: "#111111",
        "card-foreground": "#ededed",
        popover: "#111111",
        "popover-foreground": "#ededed",
        primary: "#f5a623",
        "primary-foreground": "#000000",
        secondary: "#111111",
        "secondary-foreground": "#ededed",
        muted: "#111111",
        "muted-foreground": "#666666",
        accent: "#1a1a1a",
        "accent-foreground": "#f5a623",
        destructive: "#ee0000",
        "destructive-foreground": "#ffffff",
        border: "#333333",
        input: "#333333",
        ring: "#f5a623",
        "chart-1": "#f5a623",
        "chart-2": "#ffb84d",
        "chart-3": "#ffc966",
        "chart-4": "#ffda80",
        "chart-5": "#ffeb99",
        sidebar: "#0a0a0a",
        "sidebar-foreground": "#ededed",
        "sidebar-primary": "#f5a623",
        "sidebar-primary-foreground": "#000000",
        "sidebar-accent": "#1a1a1a",
        "sidebar-accent-foreground": "#f5a623",
        "sidebar-border": "#333333",
        "sidebar-ring": "#f5a623",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "tailwind",
    name: "Tailwind",
    swatch: ["#0f172a", "#f59e0b", "#f8fafc"],
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#0f172a",
        card: "#ffffff",
        "card-foreground": "#0f172a",
        popover: "#ffffff",
        "popover-foreground": "#0f172a",
        primary: "#d97706",
        "primary-foreground": "#ffffff",
        secondary: "#f1f5f9",
        "secondary-foreground": "#0f172a",
        muted: "#f1f5f9",
        "muted-foreground": "#64748b",
        accent: "#f1f5f9",
        "accent-foreground": "#d97706",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#e2e8f0",
        input: "#e2e8f0",
        ring: "#d97706",
        "chart-1": "#d97706",
        "chart-2": "#b45309",
        "chart-3": "#92400e",
        "chart-4": "#78350f",
        "chart-5": "#451a03",
        sidebar: "#f8fafc",
        "sidebar-foreground": "#0f172a",
        "sidebar-primary": "#d97706",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f1f5f9",
        "sidebar-accent-foreground": "#d97706",
        "sidebar-border": "#e2e8f0",
        "sidebar-ring": "#d97706",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0f172a",
        foreground: "#f8fafc",
        card: "#1e293b",
        "card-foreground": "#f8fafc",
        popover: "#1e293b",
        "popover-foreground": "#f8fafc",
        primary: "#fbbf24",
        "primary-foreground": "#0f172a",
        secondary: "#1e293b",
        "secondary-foreground": "#f8fafc",
        muted: "#1e293b",
        "muted-foreground": "#94a3b8",
        accent: "#1e3a5f",
        "accent-foreground": "#fbbf24",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#334155",
        input: "#334155",
        ring: "#fbbf24",
        "chart-1": "#fbbf24",
        "chart-2": "#f59e0b",
        "chart-3": "#d97706",
        "chart-4": "#b45309",
        "chart-5": "#92400e",
        sidebar: "#0f172a",
        "sidebar-foreground": "#f8fafc",
        "sidebar-primary": "#fbbf24",
        "sidebar-primary-foreground": "#0f172a",
        "sidebar-accent": "#1e3a5f",
        "sidebar-accent-foreground": "#fbbf24",
        "sidebar-border": "#334155",
        "sidebar-ring": "#fbbf24",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    swatch: ["#0a0e1a", "#a78bfa", "#e0e7ff"],
    styles: {
      light: {
        background: "#f8fafc",
        foreground: "#0f172a",
        card: "#ffffff",
        "card-foreground": "#0f172a",
        popover: "#ffffff",
        "popover-foreground": "#0f172a",
        primary: "#7c3aed",
        "primary-foreground": "#ffffff",
        secondary: "#eef2ff",
        "secondary-foreground": "#312e81",
        muted: "#eef2ff",
        "muted-foreground": "#6366f1",
        accent: "#e0e7ff",
        "accent-foreground": "#312e81",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "#c7d2fe",
        input: "#c7d2fe",
        ring: "#7c3aed",
        "chart-1": "#7c3aed",
        "chart-2": "#6d28d9",
        "chart-3": "#5b21b6",
        "chart-4": "#4c1d95",
        "chart-5": "#3b0764",
        sidebar: "#f1f5f9",
        "sidebar-foreground": "#0f172a",
        "sidebar-primary": "#7c3aed",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e0e7ff",
        "sidebar-accent-foreground": "#312e81",
        "sidebar-border": "#c7d2fe",
        "sidebar-ring": "#7c3aed",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0a0e1a",
        foreground: "#e0e7ff",
        card: "#111827",
        "card-foreground": "#e0e7ff",
        popover: "#111827",
        "popover-foreground": "#e0e7ff",
        primary: "#a78bfa",
        "primary-foreground": "#0a0e1a",
        secondary: "#1e1b4b",
        "secondary-foreground": "#c7d2fe",
        muted: "#1e1b4b",
        "muted-foreground": "#a5b4fc",
        accent: "#312e81",
        "accent-foreground": "#a5b4fc",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#1e1b4b",
        input: "#1e1b4b",
        ring: "#a78bfa",
        "chart-1": "#a78bfa",
        "chart-2": "#8b5cf6",
        "chart-3": "#7c3aed",
        "chart-4": "#6d28d9",
        "chart-5": "#5b21b6",
        sidebar: "#0a0e1a",
        "sidebar-foreground": "#e0e7ff",
        "sidebar-primary": "#a78bfa",
        "sidebar-primary-foreground": "#0a0e1a",
        "sidebar-accent": "#312e81",
        "sidebar-accent-foreground": "#a5b4fc",
        "sidebar-border": "#1e1b4b",
        "sidebar-ring": "#a78bfa",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "forest",
    name: "Forest",
    swatch: ["#1a2e1a", "#22c55e", "#dcfce7"],
    styles: {
      light: {
        background: "#f0fdf4",
        foreground: "#14532d",
        card: "#ffffff",
        "card-foreground": "#14532d",
        popover: "#ffffff",
        "popover-foreground": "#14532d",
        primary: "#16a34a",
        "primary-foreground": "#ffffff",
        secondary: "#dcfce7",
        "secondary-foreground": "#14532d",
        muted: "#dcfce7",
        "muted-foreground": "#15803d",
        accent: "#bbf7d0",
        "accent-foreground": "#14532d",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#bbf7d0",
        input: "#bbf7d0",
        ring: "#16a34a",
        "chart-1": "#16a34a",
        "chart-2": "#15803d",
        "chart-3": "#166534",
        "chart-4": "#14532d",
        "chart-5": "#052e16",
        sidebar: "#f0fdf4",
        "sidebar-foreground": "#14532d",
        "sidebar-primary": "#16a34a",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#bbf7d0",
        "sidebar-accent-foreground": "#14532d",
        "sidebar-border": "#bbf7d0",
        "sidebar-ring": "#16a34a",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1a2e1a",
        foreground: "#dcfce7",
        card: "#1e3a1e",
        "card-foreground": "#dcfce7",
        popover: "#1e3a1e",
        "popover-foreground": "#dcfce7",
        primary: "#4ade80",
        "primary-foreground": "#1a2e1a",
        secondary: "#1e3a1e",
        "secondary-foreground": "#dcfce7",
        muted: "#1e3a1e",
        "muted-foreground": "#86efac",
        accent: "#166534",
        "accent-foreground": "#86efac",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#166534",
        input: "#166534",
        ring: "#4ade80",
        "chart-1": "#4ade80",
        "chart-2": "#22c55e",
        "chart-3": "#16a34a",
        "chart-4": "#15803d",
        "chart-5": "#166534",
        sidebar: "#1a2e1a",
        "sidebar-foreground": "#dcfce7",
        "sidebar-primary": "#4ade80",
        "sidebar-primary-foreground": "#1a2e1a",
        "sidebar-accent": "#166534",
        "sidebar-accent-foreground": "#86efac",
        "sidebar-border": "#166534",
        "sidebar-ring": "#4ade80",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    swatch: ["#1c1017", "#f97316", "#ffedd5"],
    styles: {
      light: {
        background: "#fffbeb",
        foreground: "#431407",
        card: "#ffffff",
        "card-foreground": "#431407",
        popover: "#ffffff",
        "popover-foreground": "#431407",
        primary: "#ea580c",
        "primary-foreground": "#ffffff",
        secondary: "#ffedd5",
        "secondary-foreground": "#431407",
        muted: "#ffedd5",
        "muted-foreground": "#c2410c",
        accent: "#fed7aa",
        "accent-foreground": "#431407",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#fed7aa",
        input: "#fed7aa",
        ring: "#ea580c",
        "chart-1": "#ea580c",
        "chart-2": "#c2410c",
        "chart-3": "#9a3412",
        "chart-4": "#7c2d12",
        "chart-5": "#431407",
        sidebar: "#fffbeb",
        "sidebar-foreground": "#431407",
        "sidebar-primary": "#ea580c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fed7aa",
        "sidebar-accent-foreground": "#431407",
        "sidebar-border": "#fed7aa",
        "sidebar-ring": "#ea580c",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1c1017",
        foreground: "#ffedd5",
        card: "#271520",
        "card-foreground": "#ffedd5",
        popover: "#271520",
        "popover-foreground": "#ffedd5",
        primary: "#fb923c",
        "primary-foreground": "#1c1017",
        secondary: "#271520",
        "secondary-foreground": "#ffedd5",
        muted: "#271520",
        "muted-foreground": "#fdba74",
        accent: "#7c2d12",
        "accent-foreground": "#fdba74",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#7c2d12",
        input: "#7c2d12",
        ring: "#fb923c",
        "chart-1": "#fb923c",
        "chart-2": "#f97316",
        "chart-3": "#ea580c",
        "chart-4": "#c2410c",
        "chart-5": "#9a3412",
        sidebar: "#1c1017",
        "sidebar-foreground": "#ffedd5",
        "sidebar-primary": "#fb923c",
        "sidebar-primary-foreground": "#1c1017",
        "sidebar-accent": "#7c2d12",
        "sidebar-accent-foreground": "#fdba74",
        "sidebar-border": "#7c2d12",
        "sidebar-ring": "#fb923c",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    swatch: ["#0a1628", "#06b6d4", "#cffafe"],
    styles: {
      light: {
        background: "#f0fdfa",
        foreground: "#134e4a",
        card: "#ffffff",
        "card-foreground": "#134e4a",
        popover: "#ffffff",
        "popover-foreground": "#134e4a",
        primary: "#0891b2",
        "primary-foreground": "#ffffff",
        secondary: "#ccfbf1",
        "secondary-foreground": "#134e4a",
        muted: "#ccfbf1",
        "muted-foreground": "#0d9488",
        accent: "#99f6e4",
        "accent-foreground": "#134e4a",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#99f6e4",
        input: "#99f6e4",
        ring: "#0891b2",
        "chart-1": "#0891b2",
        "chart-2": "#0e7490",
        "chart-3": "#155e75",
        "chart-4": "#164e63",
        "chart-5": "#083344",
        sidebar: "#f0fdfa",
        "sidebar-foreground": "#134e4a",
        "sidebar-primary": "#0891b2",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#99f6e4",
        "sidebar-accent-foreground": "#134e4a",
        "sidebar-border": "#99f6e4",
        "sidebar-ring": "#0891b2",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0a1628",
        foreground: "#cffafe",
        card: "#0f2035",
        "card-foreground": "#cffafe",
        popover: "#0f2035",
        "popover-foreground": "#cffafe",
        primary: "#22d3ee",
        "primary-foreground": "#0a1628",
        secondary: "#0f2035",
        "secondary-foreground": "#cffafe",
        muted: "#0f2035",
        "muted-foreground": "#67e8f9",
        accent: "#155e75",
        "accent-foreground": "#67e8f9",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#155e75",
        input: "#155e75",
        ring: "#22d3ee",
        "chart-1": "#22d3ee",
        "chart-2": "#06b6d4",
        "chart-3": "#0891b2",
        "chart-4": "#0e7490",
        "chart-5": "#155e75",
        sidebar: "#0a1628",
        "sidebar-foreground": "#cffafe",
        "sidebar-primary": "#22d3ee",
        "sidebar-primary-foreground": "#0a1628",
        "sidebar-accent": "#155e75",
        "sidebar-accent-foreground": "#67e8f9",
        "sidebar-border": "#155e75",
        "sidebar-ring": "#22d3ee",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "rose",
    name: "Rose",
    swatch: ["#1c1019", "#f43f5e", "#ffe4e6"],
    styles: {
      light: {
        background: "#fff1f2",
        foreground: "#4c0519",
        card: "#ffffff",
        "card-foreground": "#4c0519",
        popover: "#ffffff",
        "popover-foreground": "#4c0519",
        primary: "#e11d48",
        "primary-foreground": "#ffffff",
        secondary: "#ffe4e6",
        "secondary-foreground": "#4c0519",
        muted: "#ffe4e6",
        "muted-foreground": "#be123c",
        accent: "#fecdd3",
        "accent-foreground": "#4c0519",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#fecdd3",
        input: "#fecdd3",
        ring: "#e11d48",
        "chart-1": "#e11d48",
        "chart-2": "#be123c",
        "chart-3": "#9f1239",
        "chart-4": "#881337",
        "chart-5": "#4c0519",
        sidebar: "#fff1f2",
        "sidebar-foreground": "#4c0519",
        "sidebar-primary": "#e11d48",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fecdd3",
        "sidebar-accent-foreground": "#4c0519",
        "sidebar-border": "#fecdd3",
        "sidebar-ring": "#e11d48",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1c1019",
        foreground: "#ffe4e6",
        card: "#2a1520",
        "card-foreground": "#ffe4e6",
        popover: "#2a1520",
        "popover-foreground": "#ffe4e6",
        primary: "#fb7185",
        "primary-foreground": "#1c1019",
        secondary: "#2a1520",
        "secondary-foreground": "#ffe4e6",
        muted: "#2a1520",
        "muted-foreground": "#fda4af",
        accent: "#881337",
        "accent-foreground": "#fda4af",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#881337",
        input: "#881337",
        ring: "#fb7185",
        "chart-1": "#fb7185",
        "chart-2": "#f43f5e",
        "chart-3": "#e11d48",
        "chart-4": "#be123c",
        "chart-5": "#9f1239",
        sidebar: "#1c1019",
        "sidebar-foreground": "#ffe4e6",
        "sidebar-primary": "#fb7185",
        "sidebar-primary-foreground": "#1c1019",
        "sidebar-accent": "#881337",
        "sidebar-accent-foreground": "#fda4af",
        "sidebar-border": "#881337",
        "sidebar-ring": "#fb7185",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "slate",
    name: "Slate",
    swatch: ["#0f172a", "#e2e8f0", "#1e293b"],
    styles: {
      light: {
        background: "#f8fafc",
        foreground: "#0f172a",
        card: "#ffffff",
        "card-foreground": "#0f172a",
        popover: "#ffffff",
        "popover-foreground": "#0f172a",
        primary: "#475569",
        "primary-foreground": "#ffffff",
        secondary: "#e2e8f0",
        "secondary-foreground": "#0f172a",
        muted: "#e2e8f0",
        "muted-foreground": "#64748b",
        accent: "#e2e8f0",
        "accent-foreground": "#475569",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#cbd5e1",
        input: "#cbd5e1",
        ring: "#475569",
        "chart-1": "#475569",
        "chart-2": "#334155",
        "chart-3": "#1e293b",
        "chart-4": "#0f172a",
        "chart-5": "#020617",
        sidebar: "#f1f5f9",
        "sidebar-foreground": "#0f172a",
        "sidebar-primary": "#475569",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#e2e8f0",
        "sidebar-accent-foreground": "#475569",
        "sidebar-border": "#cbd5e1",
        "sidebar-ring": "#475569",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#0f172a",
        foreground: "#e2e8f0",
        card: "#1e293b",
        "card-foreground": "#e2e8f0",
        popover: "#1e293b",
        "popover-foreground": "#e2e8f0",
        primary: "#94a3b8",
        "primary-foreground": "#0f172a",
        secondary: "#1e293b",
        "secondary-foreground": "#e2e8f0",
        muted: "#1e293b",
        "muted-foreground": "#94a3b8",
        accent: "#334155",
        "accent-foreground": "#94a3b8",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#334155",
        input: "#334155",
        ring: "#94a3b8",
        "chart-1": "#94a3b8",
        "chart-2": "#64748b",
        "chart-3": "#475569",
        "chart-4": "#334155",
        "chart-5": "#1e293b",
        sidebar: "#0f172a",
        "sidebar-foreground": "#e2e8f0",
        "sidebar-primary": "#94a3b8",
        "sidebar-primary-foreground": "#0f172a",
        "sidebar-accent": "#334155",
        "sidebar-accent-foreground": "#94a3b8",
        "sidebar-border": "#334155",
        "sidebar-ring": "#94a3b8",
        radius: "0.5rem",
      },
    },
  },
  {
    id: "amber",
    name: "Amber",
    swatch: ["#1c1408", "#f59e0b", "#fef3c7"],
    styles: {
      light: {
        background: "#fffbeb",
        foreground: "#451a03",
        card: "#ffffff",
        "card-foreground": "#451a03",
        popover: "#ffffff",
        "popover-foreground": "#451a03",
        primary: "#d97706",
        "primary-foreground": "#ffffff",
        secondary: "#fef3c7",
        "secondary-foreground": "#451a03",
        muted: "#fef3c7",
        "muted-foreground": "#b45309",
        accent: "#fde68a",
        "accent-foreground": "#451a03",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        border: "#fde68a",
        input: "#fde68a",
        ring: "#d97706",
        "chart-1": "#d97706",
        "chart-2": "#b45309",
        "chart-3": "#92400e",
        "chart-4": "#78350f",
        "chart-5": "#451a03",
        sidebar: "#fffbeb",
        "sidebar-foreground": "#451a03",
        "sidebar-primary": "#d97706",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#fde68a",
        "sidebar-accent-foreground": "#451a03",
        "sidebar-border": "#fde68a",
        "sidebar-ring": "#d97706",
        "font-sans": "Inter, sans-serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
      },
      dark: {
        background: "#1c1408",
        foreground: "#fef3c7",
        card: "#2a1f0e",
        "card-foreground": "#fef3c7",
        popover: "#2a1f0e",
        "popover-foreground": "#fef3c7",
        primary: "#fbbf24",
        "primary-foreground": "#1c1408",
        secondary: "#2a1f0e",
        "secondary-foreground": "#fef3c7",
        muted: "#2a1f0e",
        "muted-foreground": "#fcd34d",
        accent: "#92400e",
        "accent-foreground": "#fcd34d",
        destructive: "#f87171",
        "destructive-foreground": "#ffffff",
        border: "#92400e",
        input: "#92400e",
        ring: "#fbbf24",
        "chart-1": "#fbbf24",
        "chart-2": "#f59e0b",
        "chart-3": "#d97706",
        "chart-4": "#b45309",
        "chart-5": "#92400e",
        sidebar: "#1c1408",
        "sidebar-foreground": "#fef3c7",
        "sidebar-primary": "#fbbf24",
        "sidebar-primary-foreground": "#1c1408",
        "sidebar-accent": "#92400e",
        "sidebar-accent-foreground": "#fcd34d",
        "sidebar-border": "#92400e",
        "sidebar-ring": "#fbbf24",
        radius: "0.5rem",
      },
    },
  },
]

export function getThemeById(id) {
  const theme = themes.find((t) => t.id === id) || themes[0]
  return {
    ...theme,
    light: theme.styles.light,
    dark: theme.styles.dark,
  }
}
